# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - model: PrecTimeModel


exp_name: dummy
phase: test
event_threshold: 2160 # 3 hours
duration_threshold: 360 # 30 minutes
prediction_threshold: 0.5
all_training: false
weight:
  exp_name: ${exp_name}
  run_name: single

dataset:
  batch_size: 128
  window_size: 100

seed: 42
num_workers: 2
# post_process
pp:
  score_th: 0.02
  distance: 10

# feature
features:
  - "anglez"
  - "enmo"
  - "hour_sin"
  - "hour_cos"

series_ids:
  - !!null
