# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: inference
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - .@_here_: train
  - dir: local
  - model: PrecTimeModel


exp_name: dummy
phase: test
weight:
  exp_name: ${exp_name}
  run_name: single

seed: 42
batch_size: 32
num_workers: 2

# post_process
pp:
  score_th: 0.02
  distance: 10

# feature
features:
  - "anglez"
  - "enmo"
  - "hour_sin"
  - "hour_cos"

series_ids:
  - "4ac356361be9"