# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: prepare_data
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${hydra.job.override_dirname}
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/
    subdir: ${hydra.job.override_dirname}

defaults:
  - _self_

phase: train
stack_cols: 
  - "anglez"
  - "enmo"
  - "anglez_sin"
  - "anglez_cos"
  - "hour_sin"
  - "hour_cos"
  - "month_sin"
  - "month_cos"
  - "minute_cos"
  - "minute_sin"

dataset:
  batch_size: 128
  window_size: 100